return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  orientation = "isometric",
  renderorder = "right-down",
  width = 10,
  height = 10,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 2,
  nextobjectid = 1,
  properties = {},
  tilesets = {
    {
      name = "Stone",
      firstgid = 1,
      filename = nil,
      exportfilename = nil,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "../Cute_Fantasy/Tiles/Cave/Cave_Floor_Middle.png",
      imagewidth = 16,
      imageheight = 16,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = { x = 0, y = 0 },
      grid = { orientation = "orthogonal", width = 16, height = 16 },
      properties = {},
      wangsets = {},
      tilecount = 1,
      tiles = {}
    },
    {
      name = "Dirt",
      firstgid = 2,
      filename = nil,
      exportfilename = nil,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 1,
      image = "../Cute_Fantasy/Tiles/Grass/Path_Middle.png",
      imagewidth = 16,
      imageheight = 16,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = { x = 0, y = 0 },
      grid = { orientation = "orthogonal", width = 16, height = 16 },
      properties = {},
      wangsets = {},
      tilecount = 1,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 10,
      height = 10,
      id = 1,
      name = "Ground",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 2, 2, 1, 1, 1, 0,
        0, 1, 0, 0, 2, 2, 0, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 2, 2, 1, 2, 2, 1, 2, 2, 0,
        0, 2, 2, 1, 2, 2, 1, 2, 2, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 2, 2, 0, 0, 1, 0,
        0, 1, 1, 1, 2, 2, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    }
  }
}
